Update SafeQueue link to a maintained version
laravel-doctrine/laraveldoctrine.org pull request #7
Opened 2021-02-21 00:40 UTC by dpslwk

2021-02-21 08:23 UTC, eigan commented
I could merge this, but it probably won't help. I have no control over the website. 

ping @josenicomaia

2021-02-22 21:41 UTC, josenicomaia requested changes

2021-02-22 21:41 UTC, josenicomaia commented on resources/views/partials/main-nav.blade.php
> +        <a class="dropdown-item" target="_blank" href="https://github.com/digband/safe-queue">SafeQueue</a>
I am getting 404 for this page. Is it broken?
`https://github.com/digband/safe-queue`

2021-02-22 21:42 UTC, josenicomaia commented
@eigan No problem. I am follow this thread.

2021-02-22 21:47 UTC, dpslwk commented
sorry fixed the typo

do wonder if we may end up having to fork and take over the repo under the laravel-doctrine name at some point in the future

2021-02-22 21:54 UTC, josenicomaia approved these changes

2021-02-22 22:03 UTC, merged